### ISSUE TITLE
Too many dependencies 

### ISSUE THREAD

**Issue by PromiseFru** [Idadelveloper/OAuth2-Slack-App#3]
It will be best if a user was able to provide the returned callback URL by themselves to continue the OAuth flow rather than having to install and setup [ngrok](https://ngrok.com/). 

Example 
- Providing the callback_URL through an API endpoint
- Pasting in your terminal window. see an example [here](https://github.com/smswithoutborders/SMSwithoutBorders-customplatform-Twitter/tree/dev#test)

**Comment by Idadelveloper** [comment]
@PromiseFru how did you manage to get `(https://localhost:9000)`? I mean the `https`.
And even if I provide the callback uri in the terminal endpoint I still need to provide it on the site
