### ISSUE TITLE
Can't find any setup instructions 

### ISSUE THREAD

**Issue by PromiseFru** [Idadelveloper/OAuth2-Slack-App#4]
I get 
```
    import slack
ModuleNotFoundError: No module named 'slack'
```
 when i start the main app.
 
 include a requirement file or a dependency tracker

**Comment by Idadelveloper** [comment]
@PromiseFru i included links to install them in the readme file. They are about 2 dependencies.

**Comment by PromiseFru** [comment]
> @PromiseFru i included links to install them in the readme file. They are about 2 dependencies.

It's always advisable to have a dependency tracker. It's not advisable for me follow links to install dependencies. I may use a version you're not using and it'll be buggy
